rvm:
  - 1.9.3
  - 2.0.0
before_script:
  - bundle exec berks install
services :
 - memcached
script:
  - bundle exec foodcritic -f any --tags ~FC015 .
  - bundle exec rspec --color --format progress
  - bundle exec rubocop
